### ISSUE TITLE
why execute select count(*) in the beginning,can i disable it?

### ISSUE THREAD

**Issue by jintianzhouyine** [logstash-plugins/logstash-input-jdbc#318] opened 2018-12-18 02:25 UTC
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System: 5.6.14
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by danhermann** [comment] 2019-01-31 12:16
This is a duplicate of https://github.com/logstash-plugins/logstash-input-jdbc/issues/305

**Closed by danhermann** 2019-01-31 12:16 UTC
